spring:
  application:
    name: payterms
  jpa:
    hibernate:
      ddl-auto: validate
  devtools:
    restart:
      additional-exclude: db/migration/**

management:
  endpoints:
    web:
      exposure:
        include: health,info