CREATE TABLE cost_center (
     id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     code   VARCHAR(20)  NOT NULL UNIQUE,
     name   VARCHAR(100) NOT NULL,
     active BOOLEAN      NOT NULL DEFAULT TRUE
);